### ISSUE TITLE
crash on loading pre-1.18 world

### ISSUE THREAD

**Issue by mivanit** [rmichela/GiantTrees#43]
When loading a (rather old) world with `naturallyGrowTrees: true`, I get the following exception. It does not appear when loading a fresh world, or when `naturallyGrowTrees: false`. When set to false, the plugin appears to work as normal -- at any rate, I can grow a giant tree with bonemeal.

I'm using papermc 1.18.1-101, and I tested this on a fresh server with no other plugins. I'm assuming this has something to do with biomes being changed in 1.18.

```java
[21:01:03 ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: DARK_FOREST_HILLS
        at com.ryanmichela.trees.TreePopulator.isAcceptableBiome(TreePopulator.java:85) ~[GiantTrees-3.0.0-alpha.2-SNAPSHOT.jar:?]
        at com.ryanmichela.trees.TreePopulator.populate(TreePopulator.java:54) ~[GiantTrees-3.0.0-alpha.2-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:825) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.lambda$updateFutures$20(ChunkHolder.java:679) ~[?:?]
        at net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:195) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1264) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:831) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1401) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:01:04 ERROR]: This crash report has been saved to: F:\Games\mc_server\testing_serv\jar\.\crash-reports\crash-2021-12-23_21.01.04-server.txt
[21:01:04 INFO]: Stopping server
[21:01:04 INFO]: [GiantTrees] Disabling GiantTrees v3.0.0-alpha.2-SNAPSHOT
[21:01:04 INFO]: Saving players
[21:01:04 INFO]: Saving worlds
[21:01:04 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[21:01:08 ERROR]: Exception stopping the server
java.lang.NoSuchFieldError: DARK_FOREST_HILLS
        at com.ryanmichela.trees.TreePopulator.isAcceptableBiome(TreePopulator.java:85) ~[GiantTrees-3.0.0-alpha.2-SNAPSHOT.jar:?]
        at com.ryanmichela.trees.TreePopulator.populate(TreePopulator.java:54) ~[GiantTrees-3.0.0-alpha.2-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:825) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.lambda$updateFutures$20(ChunkHolder.java:679) ~[?:?]
        at net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:195) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1264) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.level.ChunkMap.lambda$saveAllChunks$19(ChunkMap.java:901) ~[paper-1.18.1.jar:git-Paper-101]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.server.level.ChunkMap.saveAllChunks(ChunkMap.java:907) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.level.ServerChunkCache.save(ServerChunkCache.java:873) ~[?:?]
        at net.minecraft.server.level.ServerLevel.save(ServerLevel.java:1245) ~[?:?]
        at net.minecraft.server.MinecraftServer.saveAllChunks(MinecraftServer.java:952) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1064) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:800) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1315) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by njdro** [comment]
thanks @mivanit , for mention of `naturallyGrowTrees: false`, i will use this.

+1 the `DARK_FOREST_HILLS` error; otherwise, compiling is easy and it works.


brand-new 1.18.1 seed/world works until traveling to specified biome: 
```
java.lang.NoSuchFieldError: DARK_FOREST_HILLS
	at GiantTrees-3.0.0-alpha.1-SNAPSHOT.jar com.ryanmichela.trees.TreePopulator.isAcceptableBiome(TreePopulator.java:87)`
```
